pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        // 国内镜像（阿里云）
        maven {
            name = 'AliyunGradlePlugin'
            url = 'https://maven.aliyun.com/repository/gradle-plugin'
        }
        maven {
            name = 'AliyunPublic'
            url = 'https://maven.aliyun.com/repository/public'
        }
        gradlePluginPortal()
        mavenCentral()
    }
}
